version: '3.7'

services:
  my_device:
    image: ghcr.io/manticsic/kasa-reporter
    restart: always
    environment:
      FETCH_INTERVAL: 5
      DISCOVER_INTERVAL: 30
      LOGSTASH_HOST: "unknown"
      LOGSTASH_PORT: 5000
    network_mode: "host"
